title: Raluca D. Gaina, PhD
description: >
  AI Engineer, Game AI Researcher and Simulation Systems Developer.

url: "https://rdgain.github.io"
baseurl: ""

permalink: pretty

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-sitemap

author:
  name: Raluca D. Gaina
  email: ralucagaina2009@gmail.com
  github: rdgain
  linkedin: raluca-gaina
  google_scholar: tC5klQYAAAAJ
  researchgate: Raluca_Gaina

show_downloads: false

exclude:
  - README.md
  - Rakefile
  - changelog.md
  - Gemfile.lock
  - .sass-cache/
  - .idea/
  - .vscode/
  - vendor/